services:
  relay:
    container_name: wot-relay
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./templates/index.html:${INDEX_PATH}"
      - "./templates/static:${STATIC_PATH}"
    ports:
      - "3334:3334"
    restart: unless-stopped
    init: true
