services:
  relay:
    container_name: wot-relay
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./templates/index.html:/app/templates/index.html"
      - "./templates/static:/app/templates/static"
    ports:
      - "3334" # disable clearnet access
      #- "3334:3334" # enable clearnet access

  tor:
    image: lncm/tor:0.4.7.9@sha256:86c2fe9d9099e6376798979110b8b9a3ee5d8adec27289ac4a5ee892514ffe92
    container_name: wot-relay-tor
    depends_on:
      - relay
    volumes:
      - ./tor/torrc:/etc/tor/torrc
      - ./tor/data:/var/lib/tor
    restart: on-failure
    stop_grace_period: 10m30s
