services:
  wot-relay:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        RELAY_NAME: "utxo WoT relay"
        RELAY_PUBKEY: "e2ccf7cf20403f3f2a4a55b328f0de3be38558a7d5f33632fdaaefc726c1c8eb"
        RELAY_DESCRIPTION: "Only notes in utxo WoT"
        DB_PATH: "./db"
    volumes:
      - "./db:/app/db"
    ports:
      - "3334:3334"